import { House1, House2, House3, House4, House5, Profile } from "../Assets";

export const CustomerReviews = [
  {
    id: 1,
    avater: Profile,
    name: "John Doe",
    job: "Software Engineer",
    review:
      "I had an amazing experience buying my first home with this real estate agency. The process was smooth, and the staff were incredibly helpful.",
  },
  {
    id: 2,
    avater: Profile,
    name: "Jane Smith",
    job: "Graphic Designer",
    review:
      "The agents were very professional and found the perfect apartment for me. I highly recommend this company for their excellent service.",
  },
  {
    id: 3,
    avater: Profile,
    name: "Michael Brown",
    job: "Marketing Manager",
    review:
      "Thanks to their expertise, I was able to sell my house quickly and at a great price. Their attention to detail is unmatched.",
  },
  {
    id: 4,
    avater: Profile,
    name: "Emily Davis",
    job: "Content Writer",
    review:
      "From start to finish, the team made the entire buying process stress-free. I love my new home and couldn't be happier!",
  },
  {
    id: 5,
    avater: Profile,
    name: "Robert Wilson",
    job: "Financial Analyst",
    review:
      "The customer service was exceptional, and they really listened to my needs. I found the perfect office space thanks to their help.",
  },
  {
    id: 6,
    avater: Profile,
    name: "Linda Johnson",
    job: "Project Manager",
    review:
      "I was impressed by their professionalism and dedication. They made the process of buying my vacation home an enjoyable experience.",
  },
];

export const Properties = [
  {
    id: 1,
    address: "155 Dalla Homestay",
    beds: 4,
    baths: 2,
    sqft: 2032,
    type: "Family",
    price: 649900,
    image: House1,
    location: "2612 Macarthur Boulevard, Oakland",
    city: "Oakland",
    state: "CA",
    zip: "94602",
    category: "apartments",
  },
  {
    id: 2,
    address: "456 Market St, San Francisco",
    beds: 2,
    baths: 1,
    sqft: 1200,
    type: "Apartment",
    price: 450000,
    image: House2,
    location: "456 Market St, San Francisco",
    city: "San Francisco",
    state: "CA",
    zip: "94111",
    category: "apartments",
  },
  {
    id: 3,
    address: "789 Broadway, New York",
    beds: 3,
    baths: 2,
    sqft: 1500,
    type: "Condo",
    price: 750000,
    image: House3,
    location: "789 Broadway, New York",
    city: "New York",
    state: "NY",
    zip: "10003",
    category: "villa",
  },
  {
    id: 4,
    address: "1011 Grand Ave, Los Angeles",
    beds: 5,
    baths: 3,
    sqft: 3000,
    type: "House",
    price: 1200000,
    image: House4,
    location: "1011 Grand Ave, Los Angeles",
    city: "Los Angeles",
    state: "CA",
    zip: "90015",
    category: "house",
  },
  {
    id: 5,
    address: "1213 Elm St, Chicago",
    beds: 3,
    baths: 1,
    sqft: 1100,
    type: "Single",
    price: 350000,
    image: House5,
    location: "1213 Elm St, Chicago",
    city: "Chicago",
    state: "IL",
    zip: "60610",
    category: "single",
  },
  {
    id: 6,
    address: "1415 Pine St, Philadelphia",
    beds: 2,
    baths: 1,
    sqft: 900,
    type: "Apartment",
    price: 300000,
    image: House2,
    location: "1415 Pine St, Philadelphia",
    city: "Philadelphia",
    state: "PA",
    zip: "19102",
    category: "apartments",
  },
  {
    id: 7,
    address: "1415 Pine St, Philadelphia",
    beds: 4,
    baths: 2,
    sqft: 1900,
    type: "office",
    price: 300000,
    image: House3,
    location: "1415 Pine St, Philadelphia",
    city: "Philadelphia",
    state: "PA",
    zip: "19102",
    category: "office",
  },
  {
    id: 8,
    address: "1415 Pine St, Philadelphia",
    beds: 2,
    baths: 1,
    sqft: 900,
    type: "Apartment",
    price: 300000,
    image: House4,
    location: "1415 Pine St, Philadelphia",
    city: "Philadelphia",
    state: "PA",
    zip: "19102",
    category: "bungalow",
  },
  {
    id: 9,
    address: "1415 Pine St, Philadelphia",
    beds: 2,
    baths: 1,
    sqft: 900,
    type: "Apartment",
    price: 200000,
    image: House3,
    location: "1415 Pine St, Philadelphia",
    city: "Philadelphia",
    state: "PA",
    zip: "19102",
    category: "apartments",
  },
  {
    id: 10,
    address: "1415 Pine St, Philadelphia",
    beds: 2,
    baths: 1,
    sqft: 900,
    type: "Apartment",
    price: 300000,
    image: House5,
    location: "1415 Pine St, Philadelphia",
    city: "Philadelphia",
    state: "PA",
    zip: "19102",
    category: "villa",
  },
  {
    id: 11,
    address: "1415 Pine St, Philadelphia",
    beds: 2,
    baths: 1,
    sqft: 900,
    type: "Apartment",
    price: 100000,
    image: House2,
    location: "1415 Pine St, Philadelphia",
    city: "Philadelphia",
    state: "PA",
    zip: "19102",
    category: "apartments",
  },
  {
    id: 12,
    address: "1415 Pine St, Philadelphia",
    beds: 2,
    baths: 1,
    sqft: 900,
    type: "Apartment",
    price: 500000,
    image: House3,
    location: "1415 Pine St, Philadelphia",
    city: "Philadelphia",
    state: "PA",
    zip: "19102",
    category: "apartments",
  },
  {
    id: 13,
    address: "1415 Pine St, Philadelphia",
    beds: 2,
    baths: 1,
    sqft: 900,
    type: "Apartment",
    price: 400000,
    image: House1,
    location: "1415 Pine St, Philadelphia",
    city: "Philadelphia",
    state: "PA",
    zip: "19102",
    category: "apartments",
  },
  {
    id: 14,
    address: "1415 Pine St, Philadelphia",
    beds: 2,
    baths: 1,
    sqft: 900,
    type: "Apartment",
    price: 600000,
    image: House3,
    location: "1415 Pine St, Philadelphia",
    city: "Philadelphia",
    state: "PA",
    zip: "19102",
    category: "apartments",
  },
  {
    id: 15,
    address: "1415 Pine St, Philadelphia",
    beds: 2,
    baths: 1,
    sqft: 900,
    type: "Apartment",
    price: 300000,
    image: House5,
    location: "1415 Pine St, Philadelphia",
    city: "osogbo",
    state: "osun",
    zip: "19102",
    category: "apartments",
  },
];

export default Properties;
