import { House1, House2, House3, House4, House5, Profile } from "../Assets";

export const Properties = [
  {
    id: 1,
    address: "155 Dalla Homestay",
    beds: 4,
    baths: 2,
    sqft: 2032,
    type: "Family",
    price: 649900,
    image: House1,
    location: "2612 Macarthur Boulevard, Oakland",
    category: "apartments",
  },
  {
    id: 2,
    address: "155 Suit 12 Homestay",
    beds: 6,
    baths: 4,
    sqft: 6032,
    type: "Family",
    price: 64900,
    image: House2,
    location: "2612 Macarthur Boulevard, Oakland",
    category: "bungalow",
  },
  {
    id: 3,
    address: "Dalla Homestay Zone 1",
    beds: 5,
    baths: 2,
    sqft: 4032,
    type: "enterprises",
    price: 139900,
    image: House3,
    location: "2612 Macarthur Boulevard, Oakland",
    category: "office",
  },
  {
    id: 4,
    address: "155 Dalla Homestay",
    beds: 12,
    baths: 12,
    sqft: 80032,
    type: "guest",
    price: 949900,
    image: House4,
    location: "2612 Macarthur Boulevard, Oakland",
    category: "villa",
  },
  {
    id: 5,
    address: "155 Dalla Homestay",
    beds: 4,
    baths: 2,
    sqft: 2032,
    type: "Family",
    price: 649900,
    image: House5,
    location: "2612 Macarthur Boulevard, Oakland",
    category: "apartments",
  },
  {
    id: 6,
    address: "155 Dalla Homestay",
    beds: 4,
    baths: 2,
    sqft: 2032,
    type: "Family",
    price: 649900,
    image: House3,
    location: "2612 Macarthur Boulevard, Oakland",
    category: "bungalow",
  },
  {
    id: 7,
    address: "155 Dalla Homestay",
    beds: 4,
    baths: 2,
    sqft: 2032,
    type: "Family",
    price: 649900,
    image: House5,
    location: "2612 Macarthur Boulevard, Oakland",
    category: "apartments",
  },
  {
    id: 8,
    address: "155 Dalla Homestay",
    beds: 4,
    baths: 2,
    sqft: 2032,
    type: "Family",
    price: 649900,
    image: House1,
    location: "2612 Macarthur Boulevard, Oakland",
    category: "apartments",
  },
  {
    id: 9,
    address: "155 Dalla Homestay",
    beds: 4,
    baths: 2,
    sqft: 2032,
    type: "Family",
    price: 649900,
    image: House2,
    location: "2612 Macarthur Boulevard, Oakland",
    category: "apartments",
  },
];

export const CustomerReviews = [
  {
    id: 1,
    avater: Profile,
    name: "John Doe",
    job: "Software Engineer",
    review:
      "I had an amazing experience buying my first home with this real estate agency. The process was smooth, and the staff were incredibly helpful.",
  },
  {
    id: 2,
    avater: Profile,
    name: "Jane Smith",
    job: "Graphic Designer",
    review:
      "The agents were very professional and found the perfect apartment for me. I highly recommend this company for their excellent service.",
  },
  {
    id: 3,
    avater: Profile,
    name: "Michael Brown",
    job: "Marketing Manager",
    review:
      "Thanks to their expertise, I was able to sell my house quickly and at a great price. Their attention to detail is unmatched.",
  },
  {
    id: 4,
    avater: Profile,
    name: "Emily Davis",
    job: "Content Writer",
    review:
      "From start to finish, the team made the entire buying process stress-free. I love my new home and couldn't be happier!",
  },
  {
    id: 5,
    avater: Profile,
    name: "Robert Wilson",
    job: "Financial Analyst",
    review:
      "The customer service was exceptional, and they really listened to my needs. I found the perfect office space thanks to their help.",
  },
  {
    id: 6,
    avater: Profile,
    name: "Linda Johnson",
    job: "Project Manager",
    review:
      "I was impressed by their professionalism and dedication. They made the process of buying my vacation home an enjoyable experience.",
  },
];
