import {
  Agent1,
  Agent2,
  Agent3,
  Agent4,
  Agent5,
  Agent6,
  Agent7,
  Agent8,
  Agent9,
  House1,
  House2,
  House3,
  House4,
  House5,
  Profile,
} from "../Assets";

export const CustomerReviews = [
  {
    id: 1,
    avater: Profile,
    name: "John Doe",
    job: "Software Engineer",
    review:
      "I had an amazing experience buying my first home with this real estate agency. The process was smooth, and the staff were incredibly helpful.",
  },
  {
    id: 2,
    avater: Profile,
    name: "Jane Smith",
    job: "Graphic Designer",
    review:
      "The agents were very professional and found the perfect apartment for me. I highly recommend this company for their excellent service.",
  },
  {
    id: 3,
    avater: Profile,
    name: "Michael Brown",
    job: "Marketing Manager",
    review:
      "Thanks to their expertise, I was able to sell my house quickly and at a great price. Their attention to detail is unmatched.",
  },
  {
    id: 4,
    avater: Profile,
    name: "Emily Davis",
    job: "Content Writer",
    review:
      "From start to finish, the team made the entire buying process stress-free. I love my new home and couldn't be happier!",
  },
  {
    id: 5,
    avater: Profile,
    name: "Robert Wilson",
    job: "Financial Analyst",
    review:
      "The customer service was exceptional, and they really listened to my needs. I found the perfect office space thanks to their help.",
  },
  {
    id: 6,
    avater: Profile,
    name: "Linda Johnson",
    job: "Project Manager",
    review:
      "I was impressed by their professionalism and dedication. They made the process of buying my vacation home an enjoyable experience.",
  },
];

export const Properties = [
  {
    id: 1,
    address: "155 Dalla Homestay",
    beds: 4,
    baths: 2,
    sqft: 2032,
    type: "Family",
    price: 649900,
    image: House1,
    location: "2612 Macarthur Boulevard, Oakland",
    city: "Oakland",
    state: "CA",
    zip: "94602",
    category: "apartments",
    agentId: 1,
  },
  {
    id: 2,
    address: "245 Greenview",
    beds: 3,
    baths: 2,
    sqft: 1750,
    type: "Condo",
    price: 549000,
    image: House2,
    location: "1234 Elm Street, San Francisco",
    city: "San Francisco",
    state: "CA",
    zip: "94102",
    category: "condos",
    agentId: 2,
  },
  {
    id: 3,
    address: "789 Blue Ocean",
    beds: 5,
    baths: 3,
    sqft: 3500,
    type: "Villa",
    price: 999000,
    image: House3,
    location: "5678 Ocean Drive, Los Angeles",
    city: "Los Angeles",
    state: "CA",
    zip: "90001",
    category: "villas",
    agentId: 3,
  },
  {
    id: 4,
    address: "456 Red Sunset",
    beds: 2,
    baths: 1,
    sqft: 1200,
    type: "Apartment",
    price: 320000,
    image: House4,
    location: "7890 Sunset Blvd, San Diego",
    city: "San Diego",
    state: "CA",
    zip: "92101",
    category: "apartments",
    agentId: 4,
  },
  {
    id: 5,
    address: "112 Forest Path",
    beds: 3,
    baths: 2,
    sqft: 1850,
    type: "Townhouse",
    price: 450000,
    image: House5,
    location: "3210 Forest Avenue, Sacramento",
    city: "Sacramento",
    state: "CA",
    zip: "95814",
    category: "townhouses",
    agentId: 5,
  },
  {
    id: 6,
    address: "999 Mountain Retreat",
    beds: 4,
    baths: 3,
    sqft: 3000,
    type: "Cabin",
    price: 750000,
    image: House1,
    location: "9900 Mountain Road, Lake Tahoe",
    city: "Lake Tahoe",
    state: "CA",
    zip: "96150",
    category: "cabins",
    agentId: 6,
  },
  {
    id: 7,
    address: "888 Ocean View",
    beds: 3,
    baths: 2,
    sqft: 2100,
    type: "Penthouse",
    price: 1200000,
    image: House3,
    location: "4321 Ocean Avenue, Malibu",
    city: "Malibu",
    state: "CA",
    zip: "90265",
    category: "penthouses",
    agentId: 7,
  },
  {
    id: 8,
    address: "555 Urban Loft",
    beds: 2,
    baths: 1,
    sqft: 900,
    type: "Loft",
    price: 600000,
    image: House1,
    location: "5678 Main Street, Los Angeles",
    city: "Los Angeles",
    state: "CA",
    zip: "90015",
    category: "lofts",
    agentId: 8,
  },
  {
    id: 9,
    address: "777 Beach House",
    beds: 4,
    baths: 3,
    sqft: 2500,
    type: "Beach House",
    price: 1350000,
    image: House2,
    location: "7890 Beach Drive, Santa Monica",
    city: "Santa Monica",
    state: "CA",
    zip: "90401",
    category: "beach houses",
    agentId: 9,
  },
  {
    id: 10,
    address: "333 Downtown Condo",
    beds: 1,
    baths: 1,
    sqft: 800,
    type: "Condo",
    price: 350000,
    image: House3,
    location: "1234 Downtown Road, San Francisco",
    city: "San Francisco",
    state: "CA",
    zip: "94103",
    category: "condos",
    agentId: 10,
  },
  {
    id: 11,
    address: "234 Country Estate",
    beds: 6,
    baths: 5,
    sqft: 5000,
    type: "Estate",
    price: 2500000,
    image: House5,
    location: "4321 Country Lane, Napa",
    city: "Napa",
    state: "CA",
    zip: "94558",
    category: "estates",
    agentId: 1,
  },
  {
    id: 12,
    address: "678 City Apartment",
    beds: 1,
    baths: 1,
    sqft: 750,
    type: "Apartment",
    price: 300000,
    image: House2,
    location: "123 City Street, San Francisco",
    city: "San Francisco",
    state: "CA",
    zip: "94104",
    category: "apartments",
    agentId: 2,
  },
  {
    id: 13,
    address: "456 Suburban House",
    beds: 4,
    baths: 3,
    sqft: 2500,
    type: "House",
    price: 700000,
    image: House1,
    location: "456 Suburbia Lane, Fremont",
    city: "Fremont",
    state: "CA",
    zip: "94538",
    category: "houses",
    agentId: 3,
  },
  {
    id: 14,
    address: "789 Riverside Condo",
    beds: 2,
    baths: 2,
    sqft: 1100,
    type: "Condo",
    price: 425000,
    image: House4,
    location: "123 River Road, Sacramento",
    city: "Sacramento",
    state: "CA",
    zip: "95811",
    category: "condos",
    agentId: 4,
  },
  {
    id: 15,
    address: "987 Lake House",
    beds: 5,
    baths: 4,
    sqft: 3500,
    type: "House",
    price: 1500000,
    image: House5,
    location: "789 Lakeview Lane, Lake Tahoe",
    city: "Lake Tahoe",
    state: "CA",
    zip: "96151",
    category: "houses",
    agentId: 5,
  },
  {
    id: 16,
    address: "345 Cozy Cabin",
    beds: 3,
    baths: 2,
    sqft: 1600,
    type: "Cabin",
    price: 525000,
    image: House2,
    location: "1234 Cozy Road, Big Bear",
    city: "Big Bear",
    state: "CA",
    zip: "92315",
    category: "cabins",
    agentId: 6,
  },
  {
    id: 17,
    address: "234 Penthouse Suite",
    beds: 3,
    baths: 2,
    sqft: 2500,
    type: "Penthouse",
    price: 1350000,
    image: House3,
    location: "1234 High Rise, San Diego",
    city: "San Diego",
    state: "CA",
    zip: "92102",
    category: "penthouses",
    agentId: 7,
  },
  {
    id: 18,
    address: "567 City Loft",
    beds: 2,
    baths: 1,
    sqft: 950,
    type: "Loft",
    price: 625000,
    image: House1,
    location: "6789 Loft Street, Los Angeles",
    city: "Los Angeles",
    state: "CA",
    zip: "90013",
    category: "lofts",
    agentId: 8,
  },
  {
    id: 19,
    address: "789 Beachfront Property",
    beds: 5,
    baths: 4,
    sqft: 4000,
    type: "Beach House",
    price: 2000000,
    image: House4,
    location: "7890 Sand Street, Malibu",
    city: "Malibu",
    state: "CA",
    zip: "90265",
    category: "beach houses",
    agentId: 9,
  },
  {
    id: 20,
    address: "123 Skyline Condo",
    beds: 2,
    baths: 2,
    sqft: 1200,
    type: "Condo",
    price: 475000,
    image: House2,
    location: "5678 Skyline Avenue, San Francisco",
    city: "San Francisco",
    state: "CA",
    zip: "94105",
    category: "condos",
    agentId: 10,
  },
  {
    id: 21,
    address: "456 Estate Home",
    beds: 6,
    baths: 5,
    sqft: 5500,
    type: "Estate",
    price: 2800000,
    image: House3,
    location: "1234 Estate Road, Sonoma",
    city: "Sonoma",
    state: "CA",
    zip: "95476",
    category: "estates",
    agentId: 1,
  },
  {
    id: 22,
    address: "789 Downtown Apartment",
    beds: 1,
    baths: 1,
    sqft: 800,
    type: "Apartment",
    price: 350000,
    image: House1,
    location: "1234 Downtown Street, Francisco",
    city: "San Francisco",
    state: "CA",
    zip: "94107",
    category: "apartments",
    agentId: 2,
  },
  {
    id: 23,
    address: "123 Suburban Villa",
    beds: 5,
    baths: 4,
    sqft: 3700,
    type: "Villa",
    price: 975000,
    image: House5,
    location: "456 Villa Road, Fremont",
    city: "Fremont",
    state: "CA",
    zip: "94539",
    category: "villas",
    agentId: 3,
  },
  {
    id: 24,
    address: "345 Riverfront Condo",
    beds: 2,
    baths: 2,
    sqft: 1300,
    type: "Condo",
    price: 450000,
    image: House4,
    location: "123 River Road, Sacramento",
    city: "Sacramento",
    state: "CA",
    zip: "95812",
    category: "condos",
    agentId: 4,
  },
  {
    id: 25,
    address: "678 Mountain House",
    beds: 6,
    baths: 5,
    sqft: 4200,
    type: "House",
    price: 1750000,
    image: House2,
    location: "456 Mountain Road, Lake Tahoe",
    city: "Lake Tahoe",
    state: "CA",
    zip: "96152",
    category: "houses",
    agentId: 5,
  },
  {
    id: 26,
    address: "789 Cozy Cabin",
    beds: 3,
    baths: 2,
    sqft: 1800,
    type: "Cabin",
    price: 600000,
    image: House3,
    location: "1234 Cozy Lane, Big Bear",
    city: "Big Bear",
    state: "CA",
    zip: "92316",
    category: "cabins",
    agentId: 6,
  },
  {
    id: 27,
    address: "123 Penthouse",
    beds: 3,
    baths: 2,
    sqft: 2600,
    type: "Penthouse",
    price: 1400000,
    image: House4,
    location: "1234 High Rise, San Diego",
    city: "San Diego",
    state: "CA",
    zip: "92103",
    category: "penthouses",
    agentId: 7,
  },
  {
    id: 28,
    address: "456 City Loft",
    beds: 2,
    baths: 1,
    sqft: 950,
    type: "Loft",
    price: 650000,
    image: House2,
    location: "5678 Loft Avenue, Los Angeles",
    city: "Los Angeles",
    state: "CA",
    zip: "90014",
    category: "lofts",
    agentId: 8,
  },
  {
    id: 29,
    address: "678 Beachfront Villa",
    beds: 5,
    baths: 4,
    sqft: 4200,
    type: "Beach House",
    price: 2250000,
    image: House1,
    location: "7890 Sand Street, Malibu",
    city: "Malibu",
    state: "CA",
    zip: "90266",
    category: "beach houses",
    agentId: 9,
  },
  {
    id: 30,
    address: "890 Skyline Penthouse",
    beds: 3,
    baths: 2,
    sqft: 1300,
    type: "Penthouse",
    price: 500000,
    image: House5,
    location: "789 Skyline Avenue, San Francisco",
    city: "San Francisco",
    state: "CA",
    zip: "94105",
    category: "penthouses",
    agentId: 10,
  },
];

export const AgentsData = [
  {
    id: 1,
    image: Agent1,
    name: "John Doe",
    phone: "555-1234",
    email: "john.doe@example.com",
    rating: 5,
    properties: [1, 11, 21],
  },
  {
    id: 2,
    image: Agent2,
    name: "Jane Smith",
    phone: "555-5678",
    email: "jane.smith@example.com",
    rating: 4,
    properties: [2, 12, 22],
  },
  {
    id: 3,
    image: Agent3,
    name: "Robert Johnson",
    phone: "555-8765",
    email: "robert.johnson@example.com",
    rating: 4.5,
    properties: [3, 13, 23],
  },
  {
    id: 4,
    image: Agent4,
    name: "Michael Brown",
    phone: "555-4321",
    email: "michael.brown@example.com",
    rating: 5,
    properties: [4, 14, 24],
  },
  {
    id: 5,
    image: Agent5,
    name: "William Davis",
    phone: "555-6789",
    email: "william.davis@example.com",
    rating: 4,
    properties: [5, 15, 25],
  },
  {
    id: 6,
    image: Agent6,
    name: "Elizabeth Wilson",
    phone: "555-9876",
    email: "elizabeth.wilson@example.com",
    rating: 3.5,
    properties: [6, 16, 26],
  },
  {
    id: 7,
    image: Agent7,
    name: "Jennifer Moore",
    phone: "555-5432",
    email: "jennifer.moore@example.com",
    rating: 3,
    properties: [7, 17, 27],
  },
  {
    id: 8,
    image: Agent8,
    name: "Patricia Taylor",
    phone: "555-8765",
    email: "patricia.taylor@example.com",
    rating: 4.5,
    properties: [8, 18, 28],
  },
  {
    id: 9,
    image: Agent9,
    name: "Linda Anderson",
    phone: "555-6543",
    email: "linda.anderson@example.com",
    rating: 5,
    properties: [9, 19, 29],
  },
  {
    id: 10,
    image: Profile,
    name: "Barbara Thomas",
    phone: "555-3456",
    email: "barbara.thomas@example.com",
    rating: 4,
    properties: [10, 20, 30],
  },
];
